[tox]
envlist = py310, py311, lint, format, coverage

[testenv]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-dev.txt
commands =
    coverage run --source spices -m unittest -v -f
    coverage lcov -o .lcov

[testenv:lint]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    ruff format --check spices
    ruff check spices
    pydocstyle spices
    bandit -c pyproject.toml -r spices
    python -m pip install -e .
    pyright spices

[testenv:format]
skip_install = True
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    ruff format spices
    ruff check --fix --select F401,F841,I001 spices

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-dev.txt
commands =
    coverage run --source spices -m unittest -v -f
    coverage report -m
    coverage lcov -o .lcov
