[tox]
envlist = py310, py311, lint, format, coverage

[flake8]
max-complexity = 5
doctests = True

[testenv]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-dev.txt
commands =
    coverage run --source spices -m unittest -v -f
    coverage lcov -o .lcov

[testenv:lint]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    flake8 spices

[testenv:format]
skip_install = True
deps =
    -r{toxinidir}/requirements-dev.txt
commands =
    autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports spices
    autopep8 --diff --recursive --aggressive --aggressive spices

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/spices
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-dev.txt
commands =
    coverage run --source spices -m unittest -v -f
    coverage report -m
    coverage lcov -o .lcov
